name: Bump and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test:cover
      - name: report
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov

      - name: add dependencies
        run: sudo apt-get install -y jq
      - name: setup git
        run: |
          git config --global user.email "github@forand.fr"
          git config --global user.name "CI"
      - name: bump
        if: "!startsWith(github.event.head_commit.message, 'chore(version): ')"
        run: |
          git fetch --tags --force
          msg=`git log v$(cat package.json | jq -r ".version").. --format=%s | cut -d '(' -f 1 | sort -u`
          echo $msg | grep -zi "breaking" && yarn version --major --no-git-tag-version || (echo $msg | grep -z "feat" && yarn version --minor --no-git-tag-version || yarn version --patch --no-git-tag-version)
          git commit -am "chore(version): bump `cat package.json | jq -r '.version'`"
          git tag v`cat package.json | jq -r ".version"`
          git push && git push --tag

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v`cat package.json | jq -r ".version"` --notes ""

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
